export const filterData = [
  { name: "smartphones", image: require("../assets/OIP.jpg") },
  { name: "laptops", image: require("../assets/laptop.jpg") },
  { name: "fragrances", image: require("../assets/fragrance.jpg") },
  { name: "skincare", image: require("../assets/skincare.jpg") },
  { name: "groceries", image: require("../assets/grocery.jpg") },
  { name: "home-decoration", image: require("../assets/homedecor.jpg") },
  { name: "furniture", image: require("../assets/furniture.jpg") },
  { name: "tops", image: require("../assets/tops.jpg") },
  { name: "womens-dresses", image: require("../assets/womendress.jpg") },
  { name: "womens-shoes", image: require("../assets/womenshoe.jpg") },
  { name: "mens-shirts", image: require("../assets/menshirt.jpg") },
  { name: "mens-shoes", image: require("../assets/menshoe.jpg") },
  { name: "mens-watches", image: require("../assets/menwatch.jpg") },
  { name: "womens-watches", image: require("../assets/womenwatch.jpg") },
  { name: "womens-bags", image: require("../assets/womenbag.jpg") },
  { name: "womens-jewellery", image: require("../assets/jewel.jpg") },
  { name: "sunglesses", image: require("../assets/sunglass.jpg") },
  { name: "automotive", image: require("../assets/automotive.jpg") },
  { name: "motorcycle", image: require("../assets/motorcycle.jpg") },
  { name: "lighting", image: require("../assets/light.jpg") },
];
